src/Jme/ArticleBundle/Entity/Article.php
<?php
namespace Jme\ArticleBundle\Entity;

use \DateTime;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use DoctrineExtensions\Taggable\Taggable;

use Gedmo\Mapping\Annotation as Gedmo;

use Jme\TagBundle\Entity\Tag;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints AS DoctrineAssert;

/**
 * @ORM\Entity
 * @ORM\Table(name="article")
 * @ORM\Entity(repositoryClass="Jme\ArticleBundle\Repository\ArticleRepository")
 */
class Article implements Taggable
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var DateTime $created
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    protected $created;

    /**
     * @var datetime $updated
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    protected $updated;

    /**
     * @var bool
     *
     * @ORM\Column(name="published", type="boolean", nullable=true)
     */
    protected $published = false;

    /**
     * @var string
     *
     *  @ORM\Column(name="title", type="string", length=128, nullable=false)
     *
     * @Assert\NotNull()
     * @Assert\Length(
     *     min=3,
     *     max=128,
     *     minMessage="The title must have at least {{ limit }} character.|The title must have at least {{ limit }} characters.",
     *     maxMessage="The title must not have more than {{ limit }} character.|The title must not have more than {{ limit }} characters."
     * )
     */
    protected $title;

    /**
     * @var string
     *
     *  @ORM\Column(name="brief", type="string", length=500, nullable=false)
     *
     * @Assert\NotNull()
     * @Assert\Length(
     *     min=3,
     *     max=500,
     *     minMessage="The brief must have at least {{ limit }} character.|The brief must have at least {{ limit }} characters.",
     *     maxMessage="The brief must not have more than {{ limit }} character.|The brief must not have more than {{ limit }} characters."
     * )
     */
    protected $brief;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text", nullable=false)
     *
     * @Assert\NotNull()
     * @Assert\Length(
     *     min=3,
     *     minMessage="The content must have at least {{ limit }} character.|The content must have at least {{ limit }} characters."
     * )
     */
    protected $content;

    /**
     * @var ArrayCollection
     */
    protected $tags;

    /**
     * @Gedmo\Slug(fields={"title"}, unique=false, updatable=true)
     * @ORM\Column(length=128, unique=false)
     */
    protected $slug;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * @param $title
     * @return Article
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $content
     *
     * @return Article
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param string $brief
     *
     * @return Article
     */
    public function setBrief($brief)
    {
        $this->brief = $brief;

        return $this;
    }

    /**
     * @return string
     */
    public function getBrief()
    {
        return $this->brief;
    }

    /**
     * Returns the unique taggable resource type
     *
     * @return string
     */
    public function getTaggableType()
    {
        return 'article';
    }

    /**
     * Returns the unique taggable resource identifier
     *
     * @return string
     */
    public function getTaggableId()
    {
        return $this->getId();
    }

    /**
     * Returns the collection of tags for this Taggable entity
     *
     * @return Doctrine\Common\Collections\Collection
     */
    public function getTags()
    {
        $this->tags = $this->tags ?: new ArrayCollection();

        return $this->tags;
    }

    /**
     * @param Tag $tag
     * @return bool
     */
    public function hasTag(Tag $tag)
    {
        return $this->getTags()->contains($tag);
    }

    /**
     * @param array $tags
     * @return Article
     */
    public function setTags($tags)
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * @param $slug
     * @return Article
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @return string
     */
    public function getUrlId()
    {
        $slug = $this->getSlug();

        return strlen($slug) > 0 ? $slug : $this->getId();
    }

    /**
     * @param boolean $published
     *
     * @return Article
     */
    public function setPublished($published)
    {
        $this->published = $published;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getPublished()
    {
        return $this->published;
    }

    /**
     * @return boolean
     */
    public function isPublished()
    {
        return $this->getPublished();
    }

}

src/Jme/ArticleBundle/Controller/DefaultController.php
<?php

namespace Jme\ArticleBundle\Controller;

use Jme\ArticleBundle\Entity\Article;
use Jme\ArticleBundle\Form\Type\ArticleType;
use Jme\ArticleBundle\Service\ArticleService;
use Jme\ArticleBundle\Service\Exception\ArticleException;
use Jme\ArticleBundle\Service\Exception\ArticleNotFoundException;
use Jme\MainBundle\Component\Controller\BaseController;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Ciconia\Ciconia;
use Ciconia\Extension\Gfm;

class DefaultController extends BaseController
{
    public function indexAction()
    {
        return $this->render('JmeArticleBundle:Default:index.html.twig');
    }

    public function viewAction($article)
    {
		try {
			$article = $this->getArticleService()->getArticle($article);

			if (!$this->userIsLoggedIn() && !$article->isPublished()) {
				throw new NotFoundHttpException("Page not found");
			}

			return $this->render('JmeArticleBundle:Default:view.html.twig', array(
				'article' => $article,
			));
		}
		catch(ArticleNotFoundException $e) {
			throw new NotFoundHttpException("Page not found");
		}
    }

    public function removeAction($article)
    {
        try
        {
            $this->getArticleService()->removeArticleById($article);

            $this->get('session')->getFlashBag()->add(
                'notice',
                'The article was successfully removed!'
            );
        }
        catch(ArticleException $e)
        {
            $this->get('session')->getFlashBag()->add(
                'error',
                'Failed to remove article'
            );
        }

        return $this->redirectWithRoute('jme_article_latest');
    }

    public function newAction()
    {
        $form = $this->createArticleForm();

        return $this->render('JmeArticleBundle:Default:new.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    public function createAction()
    {
        $self       = $this;
        $service    = $this->getArticleService();
        $form       = $this->createArticleForm();

        return $this->processForm($form, function() use($form, $service, $self){

                $article = $service->saveByForm($form);

                $this->get('session')->getFlashBag()->add(
                    'notice',
                    $self->get('translator')->trans('article.created')
                );

                return $self->createSuccessRedirectResponse(
                    'jme_article_view', array('article' => $article->getId() )
                );
            },
            function($form) use($self) {
                return $self->render('JmeArticleBundle:Default:new.html.twig', array(
                    'form' => $form->createView(),
                ));
            }
        );
    }

    public function editAction($article)
    {
        try
        {
            $form = $this->createArticleForm($this->getArticleService()->getArticle($article));

            return $this->render('JmeArticleBundle:Default:edit.html.twig', array(
                'form' => $form->createView(),
            ));
        }
        catch(ArticleException $e)
        {
            $this->get('session')->getFlashBag()->add(
                'error',
                "Failed to open article for editing"
            );

            return $this->redirectWithRoute('jme_article_latest');
        }
    }

    public function updateAction($article)
    {
        $self = $this;
        $service = $this->getArticleService();

        try
        {
            $form = $this->createArticleForm($this->getArticleService()->getArticle($article));

            return $this->processForm($form, function() use($form, $service, $self) {
                    $article = $service->saveByForm($form);

                    $this->get('session')->getFlashBag()->add(
                        'notice',
                        $self->get('translator')->trans('article.updated')
                    );

                    return $self->createSuccessRedirectResponse(
                        'jme_article_view', array('article' => $article->getId() )
                    );
            },
            function($form) use($self)
            {
                return $self->render('JmeArticleBundle:Default:edit.html.twig', array(
                    'form' => $form->createView(),
                ));
            });
        }
        catch(ArticleException $e)
        {
            $this->get('session')->getFlashBag()->add(
                'error',
                "Failed to update article"
            );

            return $this->redirectWithRoute('jme_article_latest');
        }
    }

    public function latestAction()
    {
        $articles = $this->getArticleService()->listArticles(5);

        return $this->render('JmeArticleBundle:Default:latest.html.twig', array(
            'articles' => $articles,
        ));
    }

    /**
     * @param Article $article
     *
     * @return Form
     */
    protected function createArticleForm(Article $article = null)
    {
        return $this->createForm(new ArticleType(), $article);
    }

    /**
     * @return ArticleService
     */
    protected function getArticleService()
    {
        return $this->get('jme_article.service.article');
    }
}

src/Jme/ArticleBundle/Resources/views/Default/article-form-content.html.twig
<div class="buttons">
    <input type="submit" class="btn btn-primary btn-lg" value="{{ 'article.save'|trans }}" />
</div>

{{ form_widget(form) }}

<div class="buttons">
    <input type="submit" class="btn btn-primary btn-lg" value="{{ 'article.save'|trans }}" />
</div>

src/Jme/ArticleBundle/Resources/views/Default/article.html.twig
<section class="articles">
    <article>
        {% if listMode == false %}
            <h1>{{article.title}}{% if article.isPublished == false %} ({{ 'article.not-published'|trans|upper }}){% endif %}</h1>
        {% else %}
            <a class="title-link" href="{{ path('jme_article_view', {article: article.urlId}) }}">
                <h2>{{article.title}}{% if article.isPublished == false %} ({{ 'article.not-published'|trans|upper }}){% endif %}</h2>
            </a>
        {% endif %}

        <p class="date">{{article.created|date('F j, Y H:i')}} {{ jme_tags(article) }}</p>

        {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
            {{jme_article_controls(article)}}
        {% endif %}

        {% if listMode == true %}
            <div class="brief">{{article.brief|markdown}}</div>
        {% else %}
            {{article.content|markdown}}
        {% endif %}
    </article>
</section>

src/Jme/ArticleBundle/Resources/views/Default/edit.html.twig
{% extends 'JmeArticleBundle::layout.html.twig' %}

{% block content %}
    <div class="content padded-content">
        <h1>{{'article.update'|trans}}</h1>

        <div id="new-article">
            <form action="{{ path('jme_article_update', {article: form.vars['value'].id})  }}" method="post" {{ form_enctype(form) }} novalidate>
                {% include 'JmeArticleBundle:Default:article-form-content.html.twig' %}
            </form>
        </div>
    </div>
{% endblock %}

src/Jme/ArticleBundle/Resources/views/Default/index.html.twig
{% extends 'JmeArticleBundle::layout.html.twig' %}

{% block content %}


{% endblock %}

src/Jme/ArticleBundle/Resources/views/Default/latest.html.twig
{% extends 'JmeArticleBundle::layout.html.twig' %}

{% block title %}{{ jme_page_title("") }}{% endblock %}

{% block content %}

    {% if articles|length > 0 %}
        <div class="content padded-content" id="a-home">
            {% for article in articles %}
                {% include 'JmeArticleBundle:Default:article.html.twig' with {article: article, listMode: true} %}
            {% endfor %}
        </div>
    {% endif %}
    {% include 'JmeMainBundle:Default:about-inner.html.twig' %}

    {% include 'JmeMainBundle:Default:projects-inner.html.twig' %}

{% endblock %}

src/Jme/ArticleBundle/Resources/views/Default/new.html.twig
{% extends 'JmeArticleBundle::layout.html.twig' %}

{% block content %}
    <div class="content padded-content">
        <h1>{{'article.new'|trans}}</h1>

        <div id="new-article">
            <form action="{{ path('jme_article_create') }}" method="post" {{ form_enctype(form) }} novalidate>
                {% include 'JmeArticleBundle:Default:article-form-content.html.twig' %}
            </form>
        </div>
    </div>
{% endblock %}

src/Jme/ArticleBundle/Resources/views/Default/view.html.twig
{% extends 'JmeArticleBundle::layout.html.twig' %}

{% block title %}{{ jme_page_title(article.title) }}{% endblock %}

{% block content %}
    <div class="content padded-content">
        {% include 'JmeArticleBundle:Default:article.html.twig' with {article: article, listMode: false} %}

        <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'janimattiellonen-com'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </div>
{% endblock %}